{ ... }:

{
  programs.hyprlock = {
    enable = true;
    extraConfig = ''
      # This configuration is generated by matugen
      # Changing these variables with matugen still enabled will overwrite them.
      $text_color = rgba(eeddeeFF)
      $entry_background_color = rgba(21182411)
      $entry_border_color = rgba(94909155)
      $entry_color = rgba(eeddeeFF)
      $font_family = Rubik
      $font_family_clock = Space Grotesk DemiBold
      $font_material_symbols = Material Symbols Rounded
      $font = JetBrainsMono Nerd Font
      general {
        hide_cursor = true
      }
      background {
        monitor =
        path = ~/.current.wall
        blur_passes = 2
        blur_size = 5
      }
      label {
        monitor =
        text = cmd[update:1000] echo "$(date +"%A, %d %b")"
        color = rgb($foreground)
        font_size = 60
        font_family = $font
        position = 0, 375
        halign = center
        valign = center
      }
      label {
        monitor =
        text = cmd[update:1000] echo -e "$(date +"%H")"
        color = rgb($primary)
        font_size = 120
        font_family = $font, extrabold
        position = -15, 180
        halign = center
        valign = center
      }
      label {
        monitor =
        text = cmd[update:1000] echo -e "$(date +"%M")"
        color = rgb($foreground)
        font_size = 120
        font_family = $font, extrabold
        position = 15, 45
        halign = center
        valign = center
      }
      input-field {
        monitor =
        size = 300, 60
        outline_thickness = 4
        dots_size = 0.2
        dots_spacing = 0.2
        dots_center = true
        outer_color = rgb($primary)
        inner_color = rgb($background)
        font_color = rgb($foreground)
        fade_on_empty = false
        placeholder_text = <span foreground="##$foreground"><i>󰌾 Logged in as </i><spn" "foreground="##$primary">$USER</span></span>
        hide_input = false
        check_color = rgb($primary)
        fail_color = rgb($red)
        fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
        capslock_color = rgb($red)
        position = 0, -420
        halign = center
        valign = center
      }
    '';
  };
}
