# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  home:
    desc: Rebuilds the home-manager config
    summary: Rebuild a home configuration for a specific user. E.G. `task home -- angus`
    cmd: home-manager switch --flake .#"{{index .CLI_ARGS_LIST 0}}"

  system:
    desc: Rebuilds the NixOS system config
    summary: Rebuild a system configuration for a specific user. E.G. `task home -- nixos`
    cmd: sudo nixos-rebuild switch --flake .#"{{index .CLI_ARGS_LIST 0}}"

  clean:
    cmds:
      - task: clean-garbage
      - task: clean-store

  clean-garbage:
    desc: Clean up nixos previous generations gaarbage
    cmd: sudo nix-collect-garbage -d

  clean-store:
    cmd: sudo nix-store --optimise
