{ pkgs, ... }:
{
  programs.vscode.profiles.nix = {
    extensions = with pkgs.vscode-extensions; [
      # TODO: fix marketplace not working
      # aaron-bond.better-comments
      # ardenivanov.svelte-intellisense
      # astro-build.astro-vscode
      # bbugh.change-color-format
      # bierner.comment-tagged-templates
      # bierner.github-markdown-preview
      # bierner.markdown-checkbox
      # bierner.markdown-emoji
      # bierner.markdown-footnotes
      # bierner.markdown-mermaid
      # bierner.markdown-preview-github-styles
      # bradlc.vscode-tailwindcss
      # chadalen.vscode-jetbrains-icon-theme
      # christian-kohler.npm-intellisense
      # christian-kohler.path-intellisense
      # chrmarti.regex
      # codezombiech.gitignore
      # cweijan.dbclient-jdbc
      # cweijan.vscode-mysql-client2
      # dbaeumer.vscode-eslint
      # denoland.vscode-deno
      # eamodio.gitlens
      # ecmel.vscode-html-css
      # editorconfig.editorconfig
      # esbenp.prettier-vscode
      # formulahendry.auto-close-tag
      # formulahendry.auto-rename-tag
      # formulahendry.code-runner
      # github.copilot
      # github.copilot-chat
      # github.github-vscode-theme
      # github.vscode-github-actions
      # github.vscode-pull-request-github
      # grapecity.gc-excelviewer
      # hextorgb.hex-to-rgb
      # ibm.output-colorizer
      # inlang.vs-code-extension
      # ionutvmi.path-autocomplete
      # jakobkruse.svelte-kit-snippets
      # jock.svg
      # kamikillerto.vscode-colorize
      # kisstkondoros.vscode-gutter-preview
      # lokalise.i18n-ally
      # mads-hartmann.bash-ide-vscode
      # maptz.camelcasenavigation
      # mechatroner.rainbow-csv
      # meganrogge.template-string-converter
      # mikestead.dotenv
      # monish.regexsnippets
      # mrmlnc.vscode-scss
      # ms-azuretools.vscode-containers
      # ms-azuretools.vscode-docker
      # ms-ceintl.vscode-language-pack-fr
      # ms-playwright.playwright
      # ms-python.debugpy
      # ms-python.python
      # ms-python.vscode-pylance
      # ms-python.vscode-python-envs
      # ms-toolsai.jupyter
      # ms-toolsai.jupyter-keymap
      # ms-toolsai.jupyter-renderers
      # ms-toolsai.vscode-jupyter-cell-tags
      # ms-toolsai.vscode-jupyter-slideshow
      # ms-vscode-remote.remote-containers
      # ms-vscode-remote.remote-ssh
      # ms-vscode-remote.remote-ssh-edit
      # ms-vscode-remote.vscode-remote-extensionpack
      # ms-vscode.remote-explorer
      # ms-vscode.remote-server
      # ms-vscode.vscode-speech
      # nhoizey.gremlins
      # orta.vscode-jest
      # pflannery.vscode-versionlens
      # postman.postman-for-vscode
      # pranaygp.vscode-css-peek
      # quentinguidee.gitignore-ultimate
      # qwtel.sqlite-viewer
      # rakib13332.material-code
      # redhat.vscode-xml
      # sanjulaganepola.github-local-actions
      # selemondev.vscode-shadcn-svelte
      # shd101wyy.markdown-preview-enhanced
      # sibiraj-s.vscode-scss-formatter
      # simonsiefke.svg-preview
      # streetsidesoftware.code-spell-checker
      # streetsidesoftware.code-spell-checker-french
      # stylelint.vscode-stylelint
      # svelte.svelte-vscode
      # talhabalaj.actual-font-changer
      # tomoki1207.pdf
      # usernamehw.errorlens
      # vincaslt.highlight-matching-tag
      # vitest.explorer
      # wallabyjs.console-ninja
      # wix.vscode-import-cost
      # xabikos.javascriptsnippets
      # yoavbls.pretty-ts-errors
      # yzhang.markdown-all-in-one
      # zignd.html-css-class-completion
    ];
  };
}
